# Generated by Django 5.0.2 on 2024-02-15 16:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_Name', models.CharField(max_length=30, verbose_name='Наименование точки')),
                ('Point_Coordinates', models.CharField(max_length=50, verbose_name='Координаты точки')),
                ('Point_Description', models.CharField(max_length=128, verbose_name='Описание точки')),
                ('Point_Created_At', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания точки')),
                ('Point_Type', models.CharField(max_length=128, verbose_name='Описание точки')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=35, verbose_name='Почта')),
                ('role_name', models.CharField(max_length=20, verbose_name='Роль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField(verbose_name='Фото')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfishing.points')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fish_Type', models.CharField(max_length=30, verbose_name='Вид рыбы')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfishing.points')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_Type', models.CharField(max_length=30, verbose_name='Вид рыбы')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfishing.points')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='Текст сообщения')),
                ('Reply_Created_At', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания комментария')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfishing.points')),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfishing.users'),
        ),
    ]
