# Generated by Django 5.0.2 on 2024-02-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfishing', '0002_remove_photos_point_remove_points_creator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
