# Generated by Django 5.0.2 on 2024-02-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfishing', '0003_delete_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Снасти', max_length=30, verbose_name='Инструмент')),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfishing.point')),
            ],
        ),
    ]
