# Generated by Django 5.0.2 on 2024-02-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfishing', '0004_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='point_id',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='point_id',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='point_id',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='point_id',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='user_id',
            new_name='user',
        ),
    ]
