# Generated by Django 5.0.2 on 2024-02-22 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfishing', '0005_rename_point_id_comment_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
