# Generated by Django 5.0.2 on 2024-02-22 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfishing', '0006_alter_point_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
