# Generated by Django 5.0.2 on 2024-03-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfishing', '0007_alter_point_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='coordinates',
        ),
    ]
